### ISSUE TITLE
[Bug]: Package does not load in python 3.13

### ISSUE THREAD

**Issue by adamsardar** [lvgig/model_interpreter#6]
### What happened?

Package is unable to build and run tests on py313, but works fine in py312

### Environment

See below. Executed on linux (ubuntu 2202)

### Minimum reproducible code

```shell
$ uv run --with pytest --with-requirements requirements-dev.txt -p 3.12 pytest .
================================================= test session starts =================================================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
benchmark: 5.1.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/adam/model_interpreter
configfile: pyproject.toml
plugins: hypothesis-6.119.4, mock-3.14.0, cov-6.0.0, benchmark-5.1.0
collected 97 items                                                                                                    
[ ... ]
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================== 97 passed, 358 warnings in 5.65s ===========================================


$ uv run --with pytest --with-requirements requirements-dev.txt -p 3.13 pytest .
Using CPython 3.13.0
Removed virtual environment at: .venv
Creating virtual environment at: .venv
  × Failed to download and build `llvmlite==0.43.0`
  ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1)
```

### Relevant error output

```shell
× Failed to download and build `llvmlite==0.43.0`
  ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1)
      [stdout]
      running bdist_wheel
      /home/adam/.cache/uv/builds-v0/.tmpBLJQMT/bin/python /home/adam/.cache/uv/sdists-v6/pypi/llvmlite/0.43.0/ySl2OExqibWDf-IRueIQb/src/ffi/build.py
      LLVM version...

      [stderr]
      Traceback (most recent call last):
        File "/home/adam/.cache/uv/sdists-v6/pypi/llvmlite/0.43.0/ySl2OExqibWDf-IRueIQb/src/ffi/build.py", line 235, in <module>
          main()
          ~~~~^^
        File "/home/adam/.cache/uv/sdists-v6/pypi/llvmlite/0.43.0/ySl2OExqibWDf-IRueIQb/src/ffi/build.py", line 225, in main
          main_posix('linux', '.so')
          ~~~~~~~~~~^^^^^^^^^^^^^^^^
        File "/home/adam/.cache/uv/sdists-v6/pypi/llvmlite/0.43.0/ySl2OExqibWDf-IRueIQb/src/ffi/build.py", line 142, in main_posix
          raise RuntimeError(msg) from None
      RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see:
      https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
      error: command '/home/adam/.cache/uv/builds-v0/.tmpBLJQMT/bin/python' failed with exit code 1

  help: `llvmlite` (v0.43.0) was included because `model-interpeter` (v1.0.0.post12+git.5ed23c71.dirty) depends on `shap` (v0.46.0) which depends on `numba` (v0.60.0)
        which depends on `llvmlite`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adamsardar** [comment]
Update, the error above around 'Could not find a `llvm-config` binary. ' was masking the real error.  Upon installation of full llvm (`apt install llvm`) I see the _real_ error:

> RuntimeError: Cannot install on Python version 3.13.0; only versions >=3.9,<3.13 are supported.
